spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redbus_catalog
    username: redbus
    password: redbus
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # auto?creates tables while learning
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8082               # catalog-service dev port
